name: missing_child_finder
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  tflite: ^1.1.2
  image_picker:
  camera: ^0.10.5
  geolocator: ^10.1.0
  permission_handler: ^11.0.1
  flutter_email_sender: ^6.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
   - assets/labels.txt
   - assets/model_unquant.tflite
   - assets/images/